#!/usr/bin/env python3
"""Generates src/core/Core14Widths.h from the URW base35 metrics.

The fourteen standard PDF fonts may leave /Widths out of the font dictionary,
because every reader is required to know their metrics already. Redaction has
to know them too: without them a glyph's position is guesswork, and guessed
positions decide the wrong text to remove.

The URW base35 fonts (Debian/Ubuntu: fonts-urw-base35) are metrically identical
to the Adobe originals, so the numbers below are the real ones rather than an
estimate. Run this once when the table needs regenerating; the result is
committed so that building never depends on the fonts being installed.
"""

import pathlib
import re
import sys
import unicodedata

AFM_DIR = pathlib.Path("/usr/share/fonts/type1/urw-base35")

# PDF base font -> the URW file with the same metrics.
FONTS = [
    ("Helvetica", "NimbusSans-Regular"),
    ("Helvetica-Bold", "NimbusSans-Bold"),
    ("Helvetica-Oblique", "NimbusSans-Italic"),
    ("Helvetica-BoldOblique", "NimbusSans-BoldItalic"),
    ("Times-Roman", "NimbusRoman-Regular"),
    ("Times-Bold", "NimbusRoman-Bold"),
    ("Times-Italic", "NimbusRoman-Italic"),
    ("Times-BoldItalic", "NimbusRoman-BoldItalic"),
    ("Courier", "NimbusMonoPS-Regular"),
    ("Courier-Bold", "NimbusMonoPS-Bold"),
    ("Courier-Oblique", "NimbusMonoPS-Italic"),
    ("Courier-BoldOblique", "NimbusMonoPS-BoldItalic"),
    ("Symbol", "StandardSymbolsPS"),
    ("ZapfDingbats", "D050000L"),
]

FIRST, LAST = 32, 255


def parse_afm(path):
    """Returns (code -> width, name -> width) as found in the metrics file."""
    by_code, by_name = {}, {}
    pattern = re.compile(r"C\s+(-?\d+)\s*;\s*WX\s+(-?\d+)\s*;\s*N\s+(\S+)\s*;")
    for line in path.read_text(encoding="latin-1").splitlines():
        found = pattern.match(line.strip())
        if not found:
            continue
        code, width, name = int(found.group(1)), int(found.group(2)), found.group(3)
        by_name[name] = width
        if code >= 0:
            by_code[code] = width
    return by_code, by_name


def widths_for(by_code, by_name):
    """One width per code from 32 to 255, in the encoding a reader would use.

    Codes 32 to 126 are ASCII in every encoding these fonts are used with, so
    the metrics file answers directly. For the Latin-1 letters at 192 and above
    the accented forms of these fonts advance exactly as far as the plain
    letter, which is what makes stripping the accent an exact answer rather
    than an approximation. What is left is punctuation, where the average is
    close enough to decide whether a glyph sits inside a rectangle.
    """
    known = [w for w in by_code.values() if w > 0]
    average = round(sum(known) / len(known)) if known else 500

    table = []
    for code in range(FIRST, LAST + 1):
        if 32 <= code <= 126 and code in by_code:
            table.append(by_code[code])
            continue

        width = None
        if code >= 128:
            try:
                character = bytes([code]).decode("cp1252")
            except UnicodeDecodeError:
                character = None
            if character:
                stripped = "".join(c for c in unicodedata.normalize("NFD", character)
                                   if not unicodedata.combining(c))
                if len(stripped) == 1 and 32 <= ord(stripped) <= 126:
                    width = by_code.get(ord(stripped))
        table.append(width if width is not None else average)
    return table, average


def main():
    if not AFM_DIR.is_dir():
        sys.exit(f"{AFM_DIR} is missing; install fonts-urw-base35 and run this again.")

    blocks, entries = [], []
    for pdf_name, urw_name in FONTS:
        path = AFM_DIR / f"{urw_name}.afm"
        if not path.exists():
            sys.exit(f"{path} is missing; install fonts-urw-base35 and run this again.")
        table, average = widths_for(*parse_afm(path))

        identifier = pdf_name.replace("-", "")
        rows = []
        for start in range(0, len(table), 12):
            rows.append("    " + ", ".join(f"{w:4d}" for w in table[start:start + 12]) + ",")
        blocks.append(f"constexpr quint16 {identifier}[] = {{\n" + "\n".join(rows) + "\n};")
        entries.append(f'    {{ "{pdf_name}", {identifier}, {average} }},')

    header = '''/*
    SPDX-FileCopyrightText: 2026 Tom Bueng <tombueng@gmail.com>
    SPDX-License-Identifier: MIT

    Generated by tools/generate-core14-widths.py. Do not edit by hand.

    Advance widths, in thousandths of the font size, for the fourteen standard
    PDF fonts. A document may use these without giving /Widths, because every
    reader is required to know them; so must we, or a glyph's position is a
    guess and redaction removes the wrong words.
*/
#pragma once

#include <QtTypes>

namespace ps::Core14 {

/** Codes covered by every table below. */
constexpr int firstCode = ''' + str(FIRST) + ''';
constexpr int lastCode = ''' + str(LAST) + ''';

''' + "\n\n".join(blocks) + '''

struct Entry {
    const char *name;
    const quint16 *widths;
    int averageWidth;
};

constexpr Entry table[] = {
''' + "\n".join(entries) + '''
};

} // namespace ps::Core14
'''

    out = pathlib.Path(__file__).resolve().parent.parent / "src" / "core" / "Core14Widths.h"
    out.write_text(header, encoding="utf-8")
    print(f"wrote {out} ({len(FONTS)} fonts, {LAST - FIRST + 1} codes each)")


if __name__ == "__main__":
    main()
