#!/usr/bin/env python3
"""Generates src/core/Encodings.h: the simple encodings, code to character.

A PDF that names /WinAnsiEncoding is asking for cp1252, and a PDF that names
/MacRomanEncoding is asking for Mac OS Roman. Neither is Latin-1, and the
difference is not academic:

  * WinAnsi fills 0x80 to 0x9F, which Latin-1 leaves empty. The euro sign, both
    dashes, all four curly quotes, the ellipsis and the bullet live there: the
    characters a word processor produces without being asked. Read as Latin-1
    they become C1 control codes, i.e. nothing, so every en dash in every
    extracted text turned into a replacement character.
  * MacRoman disagrees with Latin-1 across the *whole* upper half. Read as
    Latin-1, "Grüße" from a Mac-produced file comes out as "GrÅ°e".

Qt cannot help: QStringConverter deals in the Unicode encodings only. Python
has both codecs built in, so the tables are generated here rather than
transcribed, and committed so that building needs nothing.

    tools/generate-encodings.py
"""

import pathlib

# The PDF name, the Python codec, and the C++ identifier.
ENCODINGS = [
    ("WinAnsiEncoding", "cp1252", "winAnsi"),
    ("MacRomanEncoding", "mac_roman", "macRoman"),
]


def table(codec):
    """256 code points, 0 where the encoding defines nothing."""
    rows = []
    for code in range(256):
        try:
            character = bytes([code]).decode(codec)
        except (UnicodeDecodeError, ValueError):
            rows.append(0)
            continue
        rows.append(ord(character))
    return rows


def render(name, codec, identifier):
    rows = table(codec)
    body = []
    for start in range(0, 256, 8):
        chunk = ", ".join(f"0x{value:04X}" for value in rows[start:start + 8])
        body.append(f"    {chunk},")
    return (
        f"/** /{name}, i.e. {codec}. Zero where the encoding defines nothing. */\n"
        f"constexpr char16_t {identifier}[256] = {{\n" + "\n".join(body) + "\n};\n"
    )


def main():
    parts = [render(*entry) for entry in ENCODINGS]

    header = '''/*
    SPDX-FileCopyrightText: 2026 Tom Bueng <tombueng@gmail.com>
    SPDX-License-Identifier: MIT

    Generated by tools/generate-encodings.py. Do not edit by hand.

    The simple encodings a PDF can name, as code-to-character tables. Read the
    generator's comment for why Latin-1 is not a substitute for either of them.
*/
#pragma once

#include <QtTypes>

namespace ps::Encodings {

''' + "\n".join(parts) + '''
} // namespace ps::Encodings
'''

    out = pathlib.Path(__file__).resolve().parent.parent / "src" / "core" / "Encodings.h"
    out.write_text(header, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
