#!/usr/bin/env python3
"""Generates src/core/GlyphNames.h from the standard encoding vectors.

A PDF font may say what its character codes mean in three different ways, and
text editing has to understand all three or it cannot type into most real
documents. The easy way is a /ToUnicode map. The next is a named encoding. The
third, and the one the magazines and the office suites actually use, is an
/Encoding dictionary with a /Differences array of *glyph names*: code 26 is
/one.fitted, code 27 is /seven.fitted, and so on.

Turning a glyph name back into a character needs the Adobe Glyph List. Rather
than transcribe it, this asks Ghostscript to print the encoding vectors it
already ships and inverts them: the position of /eacute in WinAnsiEncoding is
the cp1252 code for é, which is the character. That covers Latin-1, the Windows
punctuation, and the standard and Mac Roman sets, which between them are what
Latin-script documents contain.

Run this when the table needs regenerating; the result is committed so building
never depends on Ghostscript being installed.
"""

import pathlib
import subprocess
import sys

# Encoding vector -> the codec whose byte values it matches.
ENCODINGS = [
    ("WinAnsiEncoding", "cp1252"),
    ("MacRomanEncoding", "mac_roman"),
    ("ISOLatin1Encoding", "latin-1"),
    ("StandardEncoding", None),  # Not a byte codec; only its ASCII range is safe.
]


def vector(name):
    """The glyph names of one encoding, in code order, straight from Ghostscript."""
    result = subprocess.run(
        ["gs", "-q", "-dNODISPLAY", "-dBATCH", "-c",
         f"/{name} /Encoding findresource {{ =only ( ) print }} forall quit"],
        capture_output=True, text=True)
    if result.returncode != 0:
        return []
    return result.stdout.split()


def main():
    if subprocess.run(["which", "gs"], capture_output=True).returncode != 0:
        sys.exit("Ghostscript is needed to read the encoding vectors.")

    # name -> character. First encoding to define a name wins, so WinAnsi (the
    # commonest by a wide margin) sets the meaning where the sets disagree.
    mapping = {}
    for name, codec in ENCODINGS:
        names = vector(name)
        if not names:
            print(f"note: {name} not available from this Ghostscript", file=sys.stderr)
            continue
        for code, glyph in enumerate(names):
            if glyph == ".notdef" or glyph in mapping:
                continue
            if codec is None:
                # StandardEncoding differs from ASCII above 126 and has no codec;
                # take only the range where it agrees with everyone.
                if not 32 <= code <= 126:
                    continue
                character = chr(code)
            else:
                try:
                    character = bytes([code]).decode(codec)
                except (UnicodeDecodeError, ValueError):
                    continue
            if character.isprintable() or character == " ":
                mapping[glyph] = character

    rows = []
    for glyph in sorted(mapping):
        codepoint = ord(mapping[glyph])
        rows.append(f'    {{ "{glyph}", 0x{codepoint:04X} }},')

    header = '''/*
    SPDX-FileCopyrightText: 2026 Tom Bueng <tombueng@gmail.com>
    SPDX-License-Identifier: MIT

    Generated by tools/generate-glyphnames.py. Do not edit by hand.

    Glyph name to character, for the fonts that describe their encoding with a
    /Differences array of names rather than with a /ToUnicode map. Without this
    the text of most real documents cannot be read back, because "/eacute" is
    just a name until something says it means é.
*/
#pragma once

#include <QtTypes>

namespace ps::GlyphNames {

struct Entry {
    const char *name;
    char16_t character;
};

/** Sorted by name, so a lookup can be a binary search. */
constexpr Entry table[] = {
''' + "\n".join(rows) + '''
};

} // namespace ps::GlyphNames
'''

    out = pathlib.Path(__file__).resolve().parent.parent / "src" / "core" / "GlyphNames.h"
    out.write_text(header, encoding="utf-8")
    print(f"wrote {out} ({len(mapping)} glyph names)")


if __name__ == "__main__":
    main()
